#!/bin/sh
# This shell script is PUBLIC DOMAIN. You may do whatever you want with it.




declare -i ID
ID=`xinput list | grep -Eio '(touchpad|glidepoint)\s*id\=[0-9]{1,2}' | grep -Eo '[0-9]{1,2}'`
declare -i STATE
STATE=`xinput list-props $ID|grep 'Device Enabled'|awk '{print $4}'`
if [ $STATE -gt "0" ]
then
xinput disable $ID


else
xinput enable $ID
    
fi


exit 0

