#!/bin/sh
# This shell script is PUBLIC DOMAIN. You may do whatever you want with it.

status=$(systemctl status tp-auto-kbbl | grep -c 'running')
lightstatus=$(cat /sys/class/leds/tpacpi::kbd_backlight/brightness)


if [[ "$status" -gt "0" ]]
then
    sudo systemctl stop tp-auto-kbbl
    pkill -SIGRTMIN+12 i3blocks &
    brightnessctl --device='tpacpi::kbd_backlight' set 0
    
else
    sudo systemctl start tp-auto-kbbl
    pkill -SIGRTMIN+12 i3blocks &
    brightnessctl --device='tpacpi::kbd_backlight' set 0
fi


exit 0



