#!/usr/bin/env bash
# This shell script is PUBLIC DOMAIN. You may do whatever you want with it.


#status=$(pgrep redshift)
status=$(pgrep redshift)
if [[ -n "$status" ]]
then
    
    #echo patay
    #redshift -x
    pkill redshift &
    #pgrep redshift | xargs -n1 kill -9 &
    #xcalib -o eDP1 ~/.bin/B140HAK01_0.icm &
    sleep 5
    pkill -SIGRTMIN+5 i3blocks &
    
else
    #echo hindi
    #redshift &
    redshift -l $(curl -s "https://location.services.mozilla.com/v1/geolocate?key=geoclue" | jq -r '"\(.location.lat):\(.location.lng)"') &
    
    pkill -SIGRTMIN+5 i3blocks &
    
fi


exit 0




