#!/usr/bin/env bash
#systemctl suspend-then-hibernate
# Only exported variables can be used within the timer's command.
export PRIMARY_DISPLAY="$(xrandr | awk '/ primary/{print $1}')"

# Run xidlehook
xidlehook \
  `# Don't lock when there's a fullscreen application` \
  --not-when-fullscreen \
  `# Don't lock when there's audio playing` \
  --not-when-audio \
  `# Dim the screen after 60 seconds, undim if user becomes active` \
  --timer 300 \
    'xset dpms force off' \
    '' \
  `# Undim & lock after 10 more seconds` \
  --timer 240 \
    'xset dpms force on; notify-send "Power Management" "System will suspend after 60 seconds" -u normal' \
    '' \
  `# Finally, suspend an hour after it locks` \
  --timer 60 \
    'systemctl suspend' \
    ''




 





 
    

